#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zc.lockfile
Version  : 1.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/f5/fe/efb94907d8b2b81c3beab1bd628ff67e310d82816b94aa00b52062727ea9/zc.lockfile-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f5/fe/efb94907d8b2b81c3beab1bd628ff67e310d82816b94aa00b52062727ea9/zc.lockfile-1.3.0.tar.gz
Summary  : Basic inter-process locks
Group    : Development/Tools
License  : ZPL-2.1
Requires: zc.lockfile-python3
Requires: zc.lockfile-license
Requires: zc.lockfile-python
Requires: setuptools
Requires: zope.testing
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
Basic inter-process locks
        *************************
        
        The zc.lockfile package provides a basic portable implementation of
        interprocess locks using lock files.  The purpose if not specifically
        to lock files, but to simply provide locks with an implementation
        based on file-locking primitives.  Of course, these locks could be
        used to mediate access to *other* files.  For example, the ZODB file
        storage implementation uses file locks to mediate access to
        file-storage database files.  The database files and lock file files
        are separate files.

%package license
Summary: license components for the zc.lockfile package.
Group: Default

%description license
license components for the zc.lockfile package.


%package python
Summary: python components for the zc.lockfile package.
Group: Default
Requires: zc.lockfile-python3

%description python
python components for the zc.lockfile package.


%package python3
Summary: python3 components for the zc.lockfile package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zc.lockfile package.


%prep
%setup -q -n zc.lockfile-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534430596
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/zc.lockfile
cp LICENSE.txt %{buildroot}/usr/share/doc/zc.lockfile/LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/zc.lockfile/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
